In [59]:
from mxnet import np, npx
from mxnet.gluon import nn

npx.set_np()

class MyDense(nn.Block):
    def __init__(self, units, in_units, **kwargs):
        super().__init__(**kwargs)
        self.weight = self.params.get('weight', shape=(in_units, units))
        self.bias = self.params.get('bias', shape=(units,))

    def forward(self, x):
        linear = np.dot(
            x, self.weight.data(ctx=x.ctx)) + self.bias.data(ctx=x.ctx)
        return npx.relu(linear)


r = 2
c = 5
X1 = np.random.uniform(size=(r,c))
X2 = np.random.uniform(size=(r,c))
X3 = np.random.uniform(size=(r,c))

for i in range(len(X1)):
    for j in range(len(X1[0])):
        X3[i][j] = X1[i][j] * X2[i][j]

print("Input:")
for i in X3:
    print(i)

print("\n")
net = nn.Sequential()
net.add(MyDense(units= 3, in_units=c))
net.add(MyDense(units= 5, in_units=3))

print("Output:")
net.initialize()
net(X3)


Input:
[0.0194021  0.00639672 0.12975658 0.10523313 0.30877054]
[1.2684712e-01 3.2368201e-01 2.2489119e-04 1.1413688e-01 4.4332191e-01]


Output:


array([[0.0303513 , 0.        , 0.05606122, 0.01546856, 0.        ],
       [0.03023084, 0.        , 0.05609899, 0.01535609, 0.        ]])